# -*- coding: utf-8 -*-
"""AI video detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPC8RgyL2BNkRCxYStRwUfiQShlcxHJR
"""

# ✅ Correct installation block for Colab
!pip install --upgrade pip
!pip install opencv-python opencv-python-headless matplotlib pandas seaborn tqdm --quiet
!pip install git+https://github.com/ultralytics/yolov5.git --quiet

# ============================
!pip install --upgrade pip
!pip install ultralytics opencv-python opencv-python-headless matplotlib pandas seaborn tqdm torchvision --quiet

import cv2
import torch
import numpy as np
import pandas as pd
import time
from tqdm import tqdm
import matplotlib.pyplot as plt
import torchvision
import torchvision.transforms as T
from IPython.display import Video, display

!mkdir -p videos outputs models
!wget -O videos/sample.mp4 "https://raw.githubusercontent.com/opencv/opencv/master/samples/data/vtest.avi"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from ultralytics import YOLO
model_yolo = YOLO("yolov5s.pt")

# 2. SSDlite (MobileNetV3)
ssd_model = torchvision.models.detection.ssdlite320_mobilenet_v3_large(pretrained=True)
ssd_model = ssd_model.to(device).eval()
transform = T.Compose([T.ToTensor()])

# 3. Haar Cascade
!wget -O models/haarcascade_frontalface_default.xml https://github.com/opencv/opencv/raw/master/data/haarcascades/haarcascade_frontalface_default.xml
haar_cascade = cv2.CascadeClassifier("models/haarcascade_frontalface_default.xml")

# 4. Faster R-CNN
faster_rcnn = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
faster_rcnn = faster_rcnn.to(device).eval()

COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag',
    'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite',
    'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana',
    'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
    'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table',
    'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
    'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

# ---- YOLOv5 ----
def run_yolov5(video_path, output_path, frame_skip=2):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, 20.0, (int(cap.get(3)), int(cap.get(4))))
    fps_list, frame_id = [], 0
    for frame_id in tqdm(range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))), desc="YOLOv5"):
        ret, frame = cap.read()
        if not ret:
            break
        if frame_id % frame_skip == 0:
            start = time.time()
            results = model_yolo(frame)
            annotated_frame = results[0].plot()
            fps_list.append(1/(time.time()-start))
            out.write(annotated_frame)
    cap.release(); out.release()
    return np.mean(fps_list)

# ---- SSDlite ----
def run_ssd(video_path, output_path, frame_skip=5):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, 20.0, (int(cap.get(3)), int(cap.get(4))))
    fps_list, frame_id = [], 0
    for frame_id in tqdm(range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))), desc="SSDlite"):
        ret, frame = cap.read()
        if not ret:
            break
        if frame_id % frame_skip == 0:
            start = time.time()
            img = transform(frame).unsqueeze(0).float().to(device)
            with torch.no_grad():
                preds = ssd_model(img)[0]
            for i, score in enumerate(preds['scores']):
                if score > 0.5:
                    box = preds['boxes'][i].detach().cpu().numpy().astype(int)
                    label = COCO_INSTANCE_CATEGORY_NAMES[preds['labels'][i]]
                    cv2.rectangle(frame, (box[0], box[1]), (box[2], box[3]), (0,255,0), 2)
                    cv2.putText(frame, f"{label} {score:.2f}", (box[0], box[1]-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
            fps_list.append(1/(time.time()-start))
            out.write(frame)
    cap.release(); out.release()
    return np.mean(fps_list)

# ---- Haar Cascade ----
def run_haar(video_path, output_path, frame_skip=3):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, 20.0, (int(cap.get(3)), int(cap.get(4))))
    fps_list, frame_id = [], 0
    for frame_id in tqdm(range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))), desc="Haar Cascade"):
        ret, frame = cap.read()
        if not ret:
            break
        if frame_id % frame_skip == 0:
            start = time.time()
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = haar_cascade.detectMultiScale(gray, 1.1, 4)
            for (x,y,w,h) in faces:
                cv2.rectangle(frame, (x,y), (x+w, y+h), (255,0,0), 2)
            fps_list.append(1/(time.time()-start))
            out.write(frame)
    cap.release(); out.release()
    return np.mean(fps_list)

# ---- Faster R-CNN ----
def run_fasterrcnn(video_path, output_path, frame_skip=10):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, 20.0, (int(cap.get(3)), int(cap.get(4))))
    fps_list, frame_id = [], 0
    for frame_id in tqdm(range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))), desc="Faster R-CNN"):
        ret, frame = cap.read()
        if not ret:
            break
        if frame_id % frame_skip == 0:
            start = time.time()
            img = transform(frame).unsqueeze(0).float().to(device)
            with torch.no_grad():
                preds = faster_rcnn(img)[0]
            for i, score in enumerate(preds['scores']):
                if score > 0.5:
                    box = preds['boxes'][i].detach().cpu().numpy().astype(int)
                    label = COCO_INSTANCE_CATEGORY_NAMES[preds['labels'][i]]
                    cv2.rectangle(frame, (box[0], box[1]), (box[2], box[3]), (0,0,255), 2)
                    cv2.putText(frame, f"{label} {score:.2f}", (box[0], box[1]-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,255), 2)
            fps_list.append(1/(time.time()-start))
            out.write(frame)
    cap.release(); out.release()
    return np.mean(fps_list)

fps_yolo = run_yolov5("videos/sample.mp4", "outputs/output_yolo.mp4")
fps_ssd = run_ssd("videos/sample.mp4", "outputs/output_ssd.mp4")
fps_haar = run_haar("videos/sample.mp4", "outputs/output_haar.mp4")
fps_frcnn = run_fasterrcnn("videos/sample.mp4", "outputs/output_frcnn.mp4")

print("\n✅ Annotated output videos saved in 'outputs/' folder:")
print(" - outputs/output_yolo.mp4")
print(" - outputs/output_ssd.mp4")
print(" - outputs/output_haar.mp4")
print(" - outputs/output_frcnn.mp4")

def show_video(path):
    display(Video(path, embed=True, width=640, height=480))

print("\n▶️ YOLOv5 Result:")
show_video("outputs/output_yolo.mp4")

print("\n▶️ SSDlite Result:")
show_video("outputs/output_ssd.mp4")

print("\n▶️ Haar Cascade Result:")
show_video("outputs/output_haar.mp4")

print("\n▶️ Faster R-CNN Result:")
show_video("outputs/output_frcnn.mp4")

data = {
    "Model": ["YOLOv5", "SSDlite (MobileNetV3)", "Haar Cascade", "Faster R-CNN"],
    "FPS (avg)": [fps_yolo, fps_ssd, fps_haar, fps_frcnn],
    "Accuracy (approx)": [0.85, 0.65, 0.4, 0.9],
    "Pros": ["High accuracy, robust", "Fast & lightweight", "Very fast, simple", "Very accurate"],
    "Cons": ["Heavier, slower on CPU", "Lower accuracy", "Only faces, simple", "Slowest"]
}

df = pd.DataFrame(data)
display(df)

best_model = df.loc[df["Accuracy (approx)"].idxmax(), "Model"]
print("\n✅ Best Model for this video:", best_model)

